services:
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: "caddy reverse-proxy --from rl2.perchbird.dev --to http://web:80"
  
  web:
    image: ghcr.io/perchbirdd/reslogger2:latest
    ports:
      - "9184:9184"
    volumes:
      - web_data:/web_data/
    env_file:
      - Production.env
    depends_on:
      - db

  db:
    image: postgres:14.15-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backup:/pg_backup/
    env_file:
      - Production.env

volumes:
  web_data:
  pg_data:
  pg_backup:
  caddy_data:
  caddy_config:
