services:
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: "caddy reverse-proxy --from rl2.perchbird.dev --to http://web:80"
  
  web:
    image: ghcr.io/perchbirdd/reslogger2:latest
    ports:
      - "9184:9184"
    volumes:
      - web_data:/web_data/
    env_file:
      - Production.env
    depends_on:
      - db
      - seq_forwarder

  db:
    image: postgres:18.0-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/
      - pg_backup:/pg_backup/
    env_file:
      - Production.env

  seq_forwarder:
    image: ghcr.io/perchbirdd/seq-forwarder:latest
    stdin_open: true
    tty: true
    env_file:
      - Production.env

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  pg_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    depends_on:
      - db
    env_file:
      - Production.env

volumes:
  web_data:
  pg_data:
  pg_backup:
  caddy_data:
  caddy_config:
